# Generated by Django 6.1 on 2026-08-13 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('word_bank', 'Word Bank'), ('match_pairs', 'Match Pairs'), ('fill_blank', 'Fill in the Blank'), ('type_answer', 'Type Answer')], max_length=50)),
                ('question', models.TextField()),
                ('answer', models.JSONField(help_text='The correct answer.')),
                ('options', models.JSONField(blank=True, help_text='List of choices/options.', null=True)),
                ('position', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
